### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AlesMrak** [do-m-en/libarchive_cpp_wrapper#1]
Domen,

there are missing files in the develop branch. The CMakeLists.txt reference archive_writer.hpp and other files which do not exists in the git.

br.
Aleš

**Comment by do-m-en** [comment]
I already fixed this but forgot to reply.

Those files were messing up only the install step - library build did not require them. Now that I have finished the writer implementation and added it to the repository this problem is solved.
